version: "3.8"
services:
    tubra:
      build:
        context: . # current directory
        dockerfile: Dockerfile
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes: #update container whenever source code changed.
        - .:/Tubra_Docker  # map everything to the app
      ports:
        - 8000:8000

      env_file:
        - .env
      restart: "on-failure"
      depends_on:
        - "postgres-db"
      networks:
        - "tubra_network"
#another serveice
    postgres-db:
      image: kartoza/postgis:12.0 
      ports:
        - 5432:5432
      volumes: #where the data is store:
        - postgres_data:/var/lib/postgresql
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      restart: "on-failure"
      networks:
        - tubra_network
networks:
    tubra_network:
      driver: bridge
volumes:
      postgres_data: