# Generated by Django 3.1 on 2021-02-23 05:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aerodrome_entity',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='aerodrome_entity',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aerodrome_entity',
            name='Entity_Condition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aerodrome_entity',
            name='Feature_Name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aerodrome_entity',
            name='Survey_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='aerodrome_entity',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
