# Generated by Django 3.1 on 2021-02-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0002_auto_20210223_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerodrome_entity',
            name='Category',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
