# Generated by Django 3.1 on 2021-02-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0003_aerodrome_entity_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerodrome_entity',
            name='Category',
        ),
    ]
