# Generated by Django 3.1 on 2021-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0004_remove_aerodrome_entity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerodrome_entity',
            name='Category',
            field=models.CharField(default='Aerodrome Builds', max_length=300),
            preserve_default=False,
        ),
    ]
