# Generated by Django 3.1 on 2021-02-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0005_aerodrome_entity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerodrome_entity',
            name='Category',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
