# Generated by Django 3.1 on 2021-02-24 06:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0006_auto_20210224_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerodrome_entity',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
