# Generated by Django 3.1 on 2021-02-24 09:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0008_aerodrome_entity_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavement_construction',
            name='Pavement_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
