# Generated by Django 3.1 on 2021-02-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0009_auto_20210224_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavement_construction',
            name='Asphalt_Thickness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Base_Material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Base_Thickness',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Binder_Thickness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Concrete_Compressive_Strength',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Drainage_Cross_Slope',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Drainage_Longitudinal_Slope',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Joint_Spacing',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Pavement_Design_Type',
            field=models.CharField(choices=[('f', 'Flexible Design'), ('r', 'Rigid Pavement')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Shoulder_Width',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Soil_CPT_Test_Result',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Soil_DCP_Test_Result',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Soil_Percolation_Rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Soil_Shear_Strength',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='SubBase_Base_Seperation_Material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='SubBase_Material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='SubBase_Thickness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Subgrade_Density',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Subgrade_Soil_Classification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Wearing_Thickness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Width',
            field=models.FloatField(null=True),
        ),
    ]
