# Generated by Django 3.1 on 2021-02-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0010_auto_20210224_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerodrome_utility_electric_cable',
            name='Aerodrome_Entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aerodrome_features.aerodrome_entity'),
        ),
        migrations.AlterField(
            model_name='aerodrome_utility_gas_line',
            name='Aerodrome_Entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aerodrome_features.aerodrome_entity'),
        ),
        migrations.AlterField(
            model_name='aerodrome_utility_pole',
            name='Aerodrome_Entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aerodrome_features.aerodrome_entity'),
        ),
        migrations.AlterField(
            model_name='aerodrome_utility_sewage_line',
            name='Aerodrome_Entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aerodrome_features.aerodrome_entity'),
        ),
        migrations.AlterField(
            model_name='aerodrome_utility_water_line',
            name='Aerodrome_Entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aerodrome_features.aerodrome_entity'),
        ),
        migrations.AlterField(
            model_name='pavement_construction',
            name='Aerodrome_Entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aerodrome_features.aerodrome_entity'),
        ),
    ]
