# Generated by Django 3.1 on 2021-08-15 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0011_auto_20210227_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerodrome_part',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
