# Generated by Django 3.1 on 2021-08-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0012_auto_20210815_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerodrome_part',
            name='geom',
        ),
    ]
