# Generated by Django 3.1 on 2021-08-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0016_auto_20210815_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerodrome_Entity_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.RenameField(
            model_name='aerodrome_entity',
            old_name='Aerodrome_Part_ID',
            new_name='Aerodrome_Part',
        ),
        migrations.RemoveField(
            model_name='aerodrome_entity',
            name='Category',
        ),
        migrations.AddField(
            model_name='aerodrome_part',
            name='category',
            field=models.ManyToManyField(to='Aerodrome_features.Aerodrome_Entity_Category'),
        ),
    ]
