# Generated by Django 3.1 on 2021-08-25 08:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0019_airport_parts_ob_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=300)),
                ('ellipsoid', models.FloatField()),
                ('altitude_EGM96', models.FloatField()),
                ('type', models.CharField(max_length=300)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'POIs',
            },
        ),
    ]
