# Generated by Django 3.1 on 2021-08-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0020_pois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pois',
            name='altitude_EGM96',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pois',
            name='ellipsoid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pois',
            name='type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
