# Generated by Django 3.1 on 2021-02-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aerodrome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility_Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Height', models.FloatField()),
                ('Aerodrome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='City', to='Aerodrome.aerodrome')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
