# Generated by Django 3.1 on 2021-02-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_Name', models.CharField(max_length=300)),
                ('Block_Arabic_Name', models.CharField(max_length=300)),
                ('Bock_Number', models.CharField(max_length=300)),
                ('Block_Class', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
