# Generated by Django 3.1 on 2021-02-23 07:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0002_city_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_blocks',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
