# Generated by Django 3.1 on 2021-02-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0004_auto_20210223_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Streets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_Name', models.CharField(max_length=100)),
                ('Street_Name_Arabic', models.CharField(max_length=100)),
                ('Street_Class', models.CharField(max_length=100)),
                ('Street_Class_Arabic', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='city_blocks',
            name='Bock_Number',
        ),
        migrations.AddField(
            model_name='city_blocks',
            name='Block_Number',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='city_blocks',
            name='Block_Class',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
