# Generated by Django 3.1 on 2021-02-23 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0005_auto_20210223_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_streets',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326),
        ),
    ]
