# Generated by Django 3.1 on 2021-02-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0008_auto_20210223_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_streets',
            name='Street_Name_Arabic',
            field=models.CharField(max_length=1000),
        ),
    ]
