# Generated by Django 3.1 on 2021-02-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0009_auto_20210223_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_streets',
            name='Street_Name_Arabic',
            field=models.CharField(max_length=100),
        ),
    ]
