# Generated by Django 3.1 on 2021-02-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0010_auto_20210223_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Name', models.CharField(max_length=100)),
                ('District_Name_Arabic', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
