# Generated by Django 3.1 on 2021-02-23 19:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0011_city_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_districts',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
