# Generated by Django 3.1 on 2021-02-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0012_city_districts_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city_districts',
            old_name='Code',
            new_name='District_Code',
        ),
    ]
