# Generated by Django 3.1 on 2021-02-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0013_auto_20210223_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_districts',
            name='District_Code',
            field=models.IntegerField(null=True),
        ),
    ]
