# Generated by Django 3.1 on 2021-02-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0014_auto_20210223_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_districts',
            name='District_Code',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
