# Generated by Django 3.1 on 2021-02-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0015_auto_20210223_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_blocks',
            name='City_Name',
            field=models.CharField(default='Port Sudan', max_length=100),
            preserve_default=False,
        ),
    ]
