# Generated by Django 3.1 on 2021-02-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0016_city_blocks_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_districts',
            name='City_Name',
            field=models.CharField(default='Port Sudan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city_streets',
            name='City_Name',
            field=models.CharField(default='Port Sudan', max_length=100),
            preserve_default=False,
        ),
    ]
