# Generated by Django 3.1 on 2021-02-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0019_city_facility_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city_facility',
            old_name='Height',
            new_name='elevation',
        ),
        migrations.AlterField(
            model_name='city_facility',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
