# Generated by Django 3.1 on 2021-02-24 08:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0020_auto_20210224_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city_facility',
            name='elevation',
        ),
        migrations.AddField(
            model_name='city_facility',
            name='Elevation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city_facility',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
            preserve_default=False,
        ),
    ]
