# Generated by Django 3.1 on 2021-02-24 08:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0021_auto_20210224_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_facility',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
