# Generated by Django 3.1 on 2021-08-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City_features', '0024_ob_urban_area_obeid_streets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obeid_streets',
            name='material',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='obeid_streets',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obeid_streets',
            name='quality',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='obeid_streets',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
