# Generated by Django 3.1 on 2021-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
        ('Aerodrome_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=13)),
                ('Role', models.CharField(max_length=100)),
                ('Current_employment_status', models.CharField(max_length=100)),
                ('Aerodrome_Entity', models.ManyToManyField(to='Aerodrome_features.Aerodrome_Entity')),
                ('Project', models.ManyToManyField(to='Project.Project')),
            ],
            options={
                'ordering': ['First_Name', 'Last_Name'],
            },
        ),
    ]
