# Generated by Django 3.1 on 2021-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0011_auto_20210227_1018'),
        ('Project', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Aerodrome_Entity',
            field=models.ManyToManyField(null=True, to='Aerodrome_features.Aerodrome_Entity'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Project',
            field=models.ManyToManyField(null=True, to='Project.Project'),
        ),
    ]
