# Generated by Django 3.1 on 2021-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0016_auto_20210815_1657'),
        ('Project', '0001_initial'),
        ('Employee', '0002_auto_20210726_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Aerodrome_Entity',
            field=models.ManyToManyField(to='Aerodrome_features.Aerodrome_Entity'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Project',
            field=models.ManyToManyField(to='Project.Project'),
        ),
    ]
