version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
        pkg-manager: pip 
      - run: |
          sudo apt update && sudo apt install -y binutils libproj-dev gdal-bin python3-gdal
          python3 -m venv venv
          . venv/bin/activate 
          pip install -r requirements.txt
          python manage.py migrate 
  db:
    docker:
      - image: circleci/postgres:latest-postgis
    environment:
      - POSTGRES_USER=circleci
    steps:
      - checkout

workflows:
  main:
    jobs:
      - db
      - build:
          requires:
            - db
