version: 2.1

orbs:
  python: circleci/python@1.2
  
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
       
  db:
    docker:
      - image: circleci/postgres:latest-postgis
    environment:
      - POSTGRES_USER=circleci
    steps:
      - checkout
  test:
    docker:
      - image: cimg/python:3.8   
    steps:
      - checkout
      - run: 
        name: run python tests
        command: |
          . venv/bin/activate
          python manage.py test

workflows:
  main:
    jobs:
      - db
      - build:
        requires:
          - db
      - test:
        requires:
          - build
