version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: |
        echo "B" 
  db:
    docker:
      - image: circleci/postgres:latest-postgis
    environment:
      - POSTGRES_USER=circleci
    steps:
      - checkout

workflows:
  main:
    jobs:
      - build
      - db
