version: 2.1
jobs:
  build:
    docker:
      - image: circleci/django
    steps:
      - checkout 
      - run: echo "trying to understand this"
  
  second_job:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "that one who called binga"
