version: 2.1

orbs:
  python: circleci/python@1.2
  
workflows:
  build_and_test:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install gdal depency
          command: | 
            sudo apt-get update \
            && sudo apt-get install -y binutils libproj-dev gdal-bin python3-gdal 
      - run:
          name: Run tests
          command: python manage.py test
