# Generated by Django 3.1 on 2021-02-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_auto_20210219_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['id']},
        ),
    ]
