# Generated by Django 3.1 on 2021-02-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_auto_20210223_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Name',
            field=models.CharField(max_length=300),
        ),
    ]
