# Generated by Django 3.1 on 2021-08-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome_features', '0018_auto_20210816_1024'),
        ('Documents', '0008_auto_20210816_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Aerodrome_Entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Documents', to='Aerodrome_features.aerodrome_entity'),
        ),
    ]
