# Generated by Django 3.1 on 2021-08-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0009_auto_20210816_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_file',
            field=models.FileField(max_length=800, upload_to='../media/documents/'),
        ),
    ]
