# Generated by Django 3.1 on 2021-02-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aerodrome', '0001_initial'),
        ('Aerodrome_features', '0001_initial'),
        ('Employee', '0001_initial'),
        ('CAD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawing',
            options={'ordering': ['Date_of_Authorization']},
        ),
        migrations.RenameField(
            model_name='drawing',
            old_name='name',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='drawing_series',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='tile_file',
        ),
        migrations.AddField(
            model_name='drawing',
            name='Aerodrome_Entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CAD_Drawing', to='Aerodrome_features.aerodrome_entity'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CAD_Drawing', to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='CAD_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='drawing',
            name='Date_of_Authorization',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='drawing',
            name='Drawing_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_series', to='CAD.drawingseries'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='Number_of_issuance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drawingseries',
            name='Aerodrome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CAD_Series', to='Aerodrome.aerodrome'),
        ),
    ]
