# Generated by Django 3.1 on 2021-02-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAD', '0002_auto_20210219_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='CAD_file',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
    ]
