# Generated by Django 3.1 on 2021-08-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAD', '0004_drawing_aerodrome_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='CAD_file',
            field=models.ImageField(max_length=700, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='Title',
            field=models.CharField(max_length=700),
        ),
    ]
