# Generated by Django 3.1 on 2021-08-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAD', '0007_auto_20210823_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='CAD_file',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to='../media/CAD/'),
        ),
    ]
