# Generated by Django 3.1 on 2021-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAD', '0008_auto_20210823_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='Drawing_category',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
