# Generated by Django 3.1 on 2021-08-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAD', '0009_drawing_drawing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='Drawing_category',
            field=models.CharField(blank=True, choices=[('L', 'Layout'), ('P', 'Profile'), ('C', 'Cross section'), ('M', 'Marking')], default='', max_length=300, null=True),
        ),
    ]
