# Generated by Django 3.1 on 2021-02-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aerodrome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=300)),
                ('Aerodrome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project', to='Aerodrome.aerodrome')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phase_Name', models.CharField(max_length=300)),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_Name', models.CharField(max_length=300)),
                ('Completion', models.BooleanField()),
                ('Phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.phase')),
            ],
        ),
    ]
