# Generated by Django 3.1 on 2021-02-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aerodrome_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Reference_File', models.FileField(upload_to='')),
                ('Aerodrome_Entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aerodrome_features.aerodrome_entity')),
            ],
        ),
    ]
